// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

const dataTalent = [
  {
    id: 1,
    photo: "https://i.pravatar.cc/150?u=a042581f4e29216704d",
    fullname: "Jamaluddin Akbar Wibowo",
    job: "Web Developer",
    location: "Jakarta",
    skills: ["PHP", "C++", "Java"],
    desk: "Tidak ada kata terlambat untuk memulai hal yang baru. Selama kita masih punya tekad dan semangat, kenapa tidak?",
  },
  {
    id: 2,
    photo: "https://i.pravatar.cc/150?u=2342581f9f29026704d",
    fullname: "Latifah Bima Wibawa",
    job: "Web Developer",
    location: "Jakarta",
    skills: ["PHP", "Javascript", "C++"],
    desk: "Jangan jadi orang yang selalu berlindung di balik orang lain.",
  },
  {
    id: 3,
    photo: "https://i.pravatar.cc/150?u=a042581f4e2o026704d",
    fullname: "Sidik Burhanuddin Wibawa",
    job: "Web Developer",
    location: "Bandung",
    skills: ["PHP", "Javascript", "React"],
    desk: "Rencana sederhana yang disusun secara matang lalu diterapkan jauh lebih baik daripada rencana besar yang terus-menerus tertunda.",
  },
  {
    id: 4,
    photo: "https://i.pravatar.cc/150?u=a042991f4e29026704d",
    fullname: "Dian Dwi Wibawa",
    job: "Web Developer",
    location: "Bandung",
    skills: [
      "PHP",
      "Javascript",
      "React",
      "Express",
      "Next",
      "Golang",
      "Tailwind",
    ],
    desk: "Masa depan adalah milik mereka yang menyiapkan hari ini.",
  },
  {
    id: 5,
    photo: "https://i.pravatar.cc/150?u=a042598f4e29026704d",
    fullname: "Darma Agung Wibowo",
    job: "Web Developer",
    location: "Semarang",
    skills: ["PHP", "Javascript", "React", "Golang", "Tailwind"],
    desk: "Jadilah pekerja keras yang selalu percaya pada kemampuan diri sendiri.",
  },
  {
    id: 6,
    photo: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    fullname: "Ruslan Ratna Wibowo",
    job: "Web Developer",
    location: "Surabaya",
    skills: ["Javascript", "React", "Material UI"],
    desk: "Kedewasaan bukan dilihat dari usia, tapi dilihat dari sikap, tindakan, dan tingkah laku.",
  },
  {
    id: 7,
    photo: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    fullname: "Annisa Latifah Wibawa",
    job: "Web Developer",
    location: "Jakarta",
    skills: ["Javascript", "React"],
    desk: "Tidak peduli dari mana dirimu berasal, tidak peduli siapa kau sebelumnya, yang terpenting adalah siapa kau hari ini.",
  },
  {
    id: 8,
    photo: "https://i.pravatar.cc/150?u=a042581f4e29026704g",
    fullname: "Agung Wangi Wibowo",
    job: "Web Developer",
    location: "Bandung",
    skills: ["Tailwind", "Javascript", "React"],
    desk: "Pertama kita membentuk kebiasaan dan kebiasaan akan membentuk kita. Kalahkan kebiasaan buruk Anda atau mereka akan mengalahkan Anda.",
  },
  {
    id: 9,
    photo: "https://i.pravatar.cc/150?u=a042581f4e29029604d",
    fullname: "Widya Faisal Wibawa",
    job: "Web Developer",
    location: "Semarang",
    skills: ["Golang", "Javascript", "React", "Bootstrap"],
    desk: "Seperti bergulat melawan seekor gorila, Anda tidak berhenti ketika Anda lelah, Anda berhenti ketika gorila tersebut lelah.",
  },
  {
    id: 10,
    photo: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    fullname: "Citra Akhmad Wibawa",
    job: "Web Developer",
    location: "Semarang",
    skills: ["Next.js", "Javascript", "React"],
    desk: "Satu-satunya batasan untk meraih mimpi kita adalah keragu-raguan kita akan hari ini. Marilah kita maju dengan keyakinan yang aktif dan kuat.",
  },
  {
    id: 11,
    photo: "https://i.pravatar.cc/150?u=a042581n7e29026704d",
    fullname: "Vina Taufik Wibowo",
    job: "Web Developer",
    location: "Yogyakarta",
    skills: ["Express.JS", "Golang", "React"],
    desk: "Jangan tanyakan pada diri Anda apa yang dibutuhkan dunia. Bertanyalah apa yang membuat Anda hidup, kemudian kerjakan karena yang dibutuhkan dunia adalah orang yang antusias.",
  },
  {
    id: 12,
    photo: "https://i.pravatar.cc/150?u=a042581f4e20026704d",
    fullname: "Yuliana Sitti Wibawa",
    job: "Web Developer",
    location: "Banten",
    skills: ["Java", "Javascript", "React", "Native"],
    desk: "Ambillah risiko yang lebih besar dari apa yang dipikirkan orang lain aman. Berilah perhatian lebih dari apa yang orang lain pikir bijak. Bermimpilah lebih dari apa yang orang lain pikir masuk akal.",
  },
  {
    id: 13,
    photo: "https://i.pravatar.cc/150?u=a042581f4d99026704d",
    fullname: "Vina Widya Wibowo",
    job: "Web Developer",
    location: "Yogyakarta",
    skills: ["Next.JS", "Javascript", "React"],
    desk: "Mengeluh hanya akan membuat hidup kita semakin tertekan, sedangkan bersyukur akan senantiasa membawa kita pada jalan kemudahan.",
  },
  {
    id: 14,
    photo: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    fullname: "Dwi Edi Wibawa",
    job: "Web Developer",
    location: "Yogyakarta",
    skills: ["PHP", "Javascript", "React", "Express"],
    desk: "Belajar memulai lagi karena hidup terus berjalan.",
  },
  {
    id: 15,
    photo: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    fullname: "Sri Dian Wibawa",
    job: "Web Developer",
    location: "Semarang",
    skills: ["PHP", "Golang", "Java", "Javascript", "React"],
    desk: "Kalau hidup sekadar hidup, babi di hutan juga hidup. Kalau kerja sekadar bekerja, kera juga bekerja.",
  },
  {
    id: 16,
    photo: "https://i.pravatar.cc/150?u=a042981f4e29026704d",
    fullname: "Guntur Yusuf Wibawa",
    job: "Web Developer",
    location: "Bali",
    skills: ["PHP", "React", "Golang"],
    desk: "Kesulitan bukanlah sesuatu yang harus diratapi terus-menerus. Tapi kesulitan sesuatu yang akan membuatmu semakin gigih dan kuat.",
  },
  {
    id: 17,
    photo: "https://i.pravatar.cc/150?u=a042555f4e29026704d",
    fullname: "Aisyah Cahya Wibowo",
    job: "Web Developer",
    location: "Banten",
    skills: ["React"],
    desk: "Tujuan hidup haruslah setinggi langit di mana semua orang ingin menggapainya, bukan seperti tanah di mana semua orang bisa menginjaknya.",
  },
  {
    id: 18,
    photo: "https://i.pravatar.cc/150?u=a902581f4e29026704d",
    fullname: "Ratu Idris Wibowo",
    job: "Web Developer",
    location: "Jakarta",
    skills: ["Javascript", "React"],
    desk: "Semakin kita mencintai diri kita sendiri, semakin kita tidak seperti orang lain dan menjadikan kita unik.",
  },
  {
    id: 19,
    photo: "https://i.pravatar.cc/150?u=a042590f4e29026704d",
    fullname: "Tirta Rahman Wibawa",
    job: "Web Developer",
    location: "Bandung",
    skills: ["PHP", "React"],
    desk: "Manusia itu bagaikan pasir di antara hamparan tanah. Ia tidak harus menjadi penting kalau tujuannya hanya untuk bertahan hidup.",
  },
  {
    id: 20,
    photo: "https://i.pravatar.cc/150?u=a042581f4e00026704d",
    fullname: "Bachtiar Nur Wibawa",
    job: "Web Developer",
    location: "Balikpapan",
    skills: ["PHP", "Javascript", "React", "Kotlin"],
    desk: "Setiap penemuan selalu menciptakan pengetahuan baru.",
  },
  {
    id: 21,
    photo: "https://i.pravatar.cc/150?u=a042581f4e90026704d",
    fullname: "Halimah Dian Wibowo",
    job: "Web Developer",
    location: "Riau",
    skills: ["PHP", "Javascript", "React", "Java"],
    desk: "Kekuatan yang diberikan oleh Tuhan untukmu tidak akan bisa untuk mengubah masa lalu. Kekuatanmu hanya untuk mengubah masa depanmu.",
  },
  {
    id: 22,
    photo: "https://i.pravatar.cc/150?u=a098581h7e29026704d",
    fullname: "Nur Ahmad Wibowo",
    job: "Web Developer",
    location: "Banten",
    skills: ["Javascript"],
    desk: "Bukan masalah kalau kamu mengerjakan sesuatu dengan lambat. Yang menjadi masalah itu kalau kamu berhenti melakukan sesuatu.",
  },
];

export default function handler(req, res) {
  if (req.query.id) {
    res
    .status(200)
    .json({ status: true, Message: "Get Data Success", Data: dataTalent?.find((item) => item?.id == req.query.id) });
  } else {

    res
    .status(200)
    .json({ status: true, Message: "Get Data Success", Data: dataTalent });
  }
  }
  